# Generated by Django 3.2.8 on 2021-11-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorName', models.CharField(max_length=30)),
                ('actorAge', models.IntegerField()),
                ('actorBir', models.CharField(max_length=30)),
                ('actorPhoto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('companyAddr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=30)),
                ('directorAge', models.IntegerField()),
                ('directorBir', models.CharField(max_length=30)),
                ('directorPhoto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('movieIntroduction', models.CharField(max_length=500)),
                ('movieDate', models.DateField()),
                ('movieStyle', models.CharField(choices=[(0, '喜剧'), (1, '悲剧')], max_length=20)),
                ('moviePhoto', models.CharField(max_length=100)),
                ('movieWard', models.CharField(max_length=30)),
                ('movieCost', models.BigIntegerField()),
                ('movieCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.company')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewGrade', models.IntegerField()),
                ('reviewString', models.CharField(max_length=200)),
                ('reviewDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('upwd', models.CharField(max_length=18)),
                ('loveActors', models.ManyToManyField(to='login.Actor')),
                ('loveDirectors', models.ManyToManyField(to='login.Director')),
                ('loveMovies', models.ManyToManyField(to='login.Movie')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewedAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.webuser'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewedMovie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.movie'),
        ),
        migrations.AddField(
            model_name='director',
            name='representativeMovies',
            field=models.ManyToManyField(to='login.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='majorActedMovies',
            field=models.ManyToManyField(to='login.Movie'),
        ),
    ]
