# Generated by Django 3.2.8 on 2021-11-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211118_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='majorActedMovies',
            field=models.ManyToManyField(null=True, to='login.Movie'),
        ),
        migrations.AlterField(
            model_name='director',
            name='representativeMovies',
            field=models.ManyToManyField(null=True, to='login.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.company'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewedAuthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.webuser'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewedMovie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.movie'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='loveActors',
            field=models.ManyToManyField(null=True, to='login.Actor'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='loveDirectors',
            field=models.ManyToManyField(null=True, to='login.Director'),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='loveMovies',
            field=models.ManyToManyField(null=True, to='login.Movie'),
        ),
    ]
